name = "remix"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks/app/uninstalled"

[commands]
predev = "npx drizzle-kit generate"
dev = "npx drizzle-kit migrate && npm exec next dev --turbopack"
